# Generated by Django 5.0 on 2025-11-17 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('delivery_bases', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(help_text='ログインIDとして使用', max_length=50, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(help_text='ユーザーの氏名', max_length=100, verbose_name='ユーザー名')),
                ('user_type', models.CharField(choices=[('BASE_STAFF', '拠点倉庫担当'), ('LC_STAFF', 'LC倉庫担当'), ('ADMIN', '管理者')], help_text='ユーザーの種類（拠点倉庫担当、LC倉庫担当、管理者）', max_length=20, verbose_name='ユーザー区分')),
                ('is_active', models.BooleanField(default=True, help_text='利用可否', verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ権限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('base_code', models.ForeignKey(blank=True, db_column='base_code', help_text='所属する配送拠点（拠点倉庫担当のみ。LC倉庫担当・管理者はNULL）', null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_bases.deliverybase', verbose_name='所属拠点コード')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
                'ordering': ['user_id'],
                'indexes': [models.Index(fields=['user_type'], name='idx_user_type'), models.Index(fields=['base_code'], name='idx_user_base')],
            },
        ),
    ]
