# Generated by Django 5.0 on 2025-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBase',
            fields=[
                ('base_code', models.CharField(help_text='拠点を一意に識別するコード（30拠点）', max_length=10, primary_key=True, serialize=False, verbose_name='拠点コード')),
                ('base_name', models.CharField(help_text='拠点の名称', max_length=100, verbose_name='拠点名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '配送拠点',
                'verbose_name_plural': '配送拠点',
                'db_table': 'delivery_base',
                'ordering': ['base_code'],
            },
        ),
    ]
