# Generated by Django 5.0 on 2025-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(help_text='商品を一意に識別するコード', max_length=20, primary_key=True, serialize=False, verbose_name='商品コード')),
                ('product_name', models.CharField(help_text='商品の名称（例：アルコーラ、アルコーヒー）', max_length=100, verbose_name='商品名')),
                ('pallet_case_quantity', models.IntegerField(help_text='1パレットあたりの標準ケース数（出庫依頼の単位チェックに使用）', verbose_name='パレット積載ケース数')),
                ('is_active', models.BooleanField(default=True, help_text='取扱中か否か', verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
                'ordering': ['product_code'],
            },
        ),
    ]
