# Generated by Django 5.0 on 2025-11-17 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_bases', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LcShipmentRequest',
            fields=[
                ('request_id', models.CharField(help_text='出庫依頼を一意に識別するID', max_length=30, primary_key=True, serialize=False, verbose_name='出庫依頼ID')),
                ('request_date', models.DateField(help_text='出庫依頼を登録した日付', verbose_name='依頼登録日')),
                ('delivery_date', models.DateField(help_text='配送拠点への配送予定日（=出庫日）。登録日の翌営業日（土日除く）を自動設定', verbose_name='配送予定日')),
                ('request_status', models.CharField(choices=[('CREATED', '作成済'), ('SENT', '送信済'), ('ERROR', 'エラー')], default='CREATED', help_text='依頼の状態（作成済、送信済、エラー）。送信完了=完了', max_length=20, verbose_name='依頼ステータス')),
                ('total_quantity', models.IntegerField(default=0, help_text='依頼全体の合計ケース数', verbose_name='合計数量')),
                ('note', models.TextField(blank=True, help_text='特記事項', null=True, verbose_name='備考')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='依頼作成日時', verbose_name='依頼作成日時')),
                ('sent_at', models.DateTimeField(blank=True, help_text='LC倉庫への送信日時', null=True, verbose_name='送信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('base_code', models.ForeignKey(db_column='base_code', help_text='配送先の拠点', on_delete=django.db.models.deletion.PROTECT, to='delivery_bases.deliverybase', verbose_name='配送拠点コード')),
                ('requested_by', models.ForeignKey(db_column='requested_by', help_text='依頼を作成したユーザーID', on_delete=django.db.models.deletion.PROTECT, related_name='requested_shipments', to=settings.AUTH_USER_MODEL, verbose_name='依頼者')),
                ('sent_by', models.ForeignKey(blank=True, db_column='sent_by', help_text='送信したLC倉庫担当のユーザーID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipments', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'LC出庫依頼',
                'verbose_name_plural': 'LC出庫依頼',
                'db_table': 'lc_shipment_request',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LcShipmentRequestDetail',
            fields=[
                ('detail_id', models.BigAutoField(help_text='明細を一意に識別するID', primary_key=True, serialize=False, verbose_name='明細ID')),
                ('line_number', models.IntegerField(help_text='依頼内での明細順序', verbose_name='明細行番号')),
                ('requested_quantity', models.IntegerField(help_text='出庫を依頼するケース数。商品マスタのパレット積載ケース数の倍数であること', verbose_name='依頼数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_code', models.ForeignKey(db_column='product_code', help_text='出庫する商品', on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品コード')),
                ('request_id', models.ForeignKey(db_column='request_id', help_text='親の出庫依頼', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shipment_requests.lcshipmentrequest', verbose_name='出庫依頼ID')),
            ],
            options={
                'verbose_name': 'LC出庫依頼明細',
                'verbose_name_plural': 'LC出庫依頼明細',
                'db_table': 'lc_shipment_request_detail',
                'ordering': ['request_id', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='lcshipmentrequest',
            index=models.Index(fields=['request_status'], name='idx_request_status'),
        ),
        migrations.AddIndex(
            model_name='lcshipmentrequest',
            index=models.Index(fields=['base_code', 'delivery_date'], name='idx_request_base_date'),
        ),
        migrations.AddIndex(
            model_name='lcshipmentrequest',
            index=models.Index(fields=['request_date'], name='idx_request_date'),
        ),
        migrations.AddIndex(
            model_name='lcshipmentrequestdetail',
            index=models.Index(fields=['request_id', 'line_number'], name='idx_detail_request'),
        ),
        migrations.AlterUniqueTogether(
            name='lcshipmentrequestdetail',
            unique_together={('request_id', 'line_number')},
        ),
    ]
